# Generated by Django 4.2.29 on 2026-06-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_ownerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner_app', '0003_evstation_operational_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_staff_members', to='home.ownerprofile')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='owner_app.evstation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='station_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('station__station_name', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='StationSlotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_statuses', to='owner_app.chargingslot')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_statuses', to='owner_app.evstation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('slot__slot_id',),
            },
        ),
        migrations.AddConstraint(
            model_name='stationstaffprofile',
            constraint=models.UniqueConstraint(fields=('station', 'employee_id'), name='unique_employee_id_per_station'),
        ),
        migrations.AddConstraint(
            model_name='stationslotstatus',
            constraint=models.UniqueConstraint(fields=('station', 'slot'), name='unique_slot_status_per_station'),
        ),
    ]
