# Generated by Django 4.2.29 on 2026-05-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_ownerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVStation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('station_type', models.CharField(max_length=50)),
                ('total_slots', models.IntegerField()),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ownerprofile')),
            ],
        ),
    ]
