# Generated by Django 4.2.29 on 2026-05-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargingslot',
            fields=[
                ('slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
            ],
        ),
    ]
