# Generated by Django 4.2.29 on 2026-06-19 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner_app', '0002_chargingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='evstation',
            name='operational_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Under maintenance'), ('offline', 'Offline')], default='closed', max_length=20),
        ),
        migrations.AddField(
            model_name='evstation',
            name='status_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evstation',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evstation',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
